### ISSUE TITLE
未使用的函数 change_xml_annotation

### ISSUE THREAD

**Issue by BackMountainDevil** [CodingWZP/image_augmentation#1]
https://github.com/CodingWZP/image_augmentation/blob/f4ed16447ca3cea09ff8849c0d5bb0b343d1a420/augmentation.py#L39

用查找查了这个函数，全文就出现了一次。只有定义没有引用，是忘记删除了买

**Comment by CodingWZP** [comment]
哈哈哈 是的 已经删除了 谢谢你~
